### PR TITLE
Fix for issue #637

### PR DESCRIPTION
**Pull request by jepsar**
Sorry for the noise caused by trim trailing spaces on save...

### CODE REVIEW

**Comment by stephanrauh** [comment]
At first glance, your PR looks good. Thanks! I don't have enough time to test it thoroughly, so I'll merge it this week-end.

Would you mind to updated the BootsFaces.jsfdsl, too? This is the file we use to generate the component classes, the taglib and much of the documentation.

Thanks in advance
Stephan

**Comment by jepsar** [comment]
I've seen BootsFaces.jsfdsl, but don't know what to change there. It's not mentioned that interval should be a string, so it looks alright as is to me.

**Comment by stephanrauh** [comment]
Well, yes, you're probably right. The default data type is String. But it's hard to get it right without installing the [eclipse plugin](https://github.com/stephanrauh/JSFLibraryGenerator). I'll care about it.

**Comment by jepsar** [comment]
I was thinking that it might be useful to have `toInteger(Object object, int defaultValue)` in the utils class. Since when reading attributes in most cases (or even all) you want to have a default value. If you agree I will add this to my fork.

**Comment by stephanrauh** [comment]
JSF already provides optional default values for component attributes, including integers and booleans. If you see a use case that's not covered by this, feel free to go ahead.

```xml
public class Column extends UIOutput ... {
   ...
   public int getTooltipDelayShow() {
     return (int) (Integer) getStateHelper().eval(PropertyKeys.tooltipDelayShow, 
                                                                            0 // default value
                                                                            );
   }
}
```

**Comment by jepsar** [comment]
OK, clear. The poll component is not written this way (it gets the attribute values from a map). I'll leave it as is.

**Comment by stephanrauh** [comment]
Thanks!

**Comment by stephanrauh** [comment]
@jepsar May I mention you in "Kudos" section of the BootsFaces 1.1.0 announcement post?

**Comment by jepsar** [comment]
@stephanrauh Sure. Glad I could help out.

**Pull request merged**
