### PR TITLE
Fix includes for Properties set with a ValueExpression

### PR DESCRIPTION
**Pull request by stjheitc**
if a valueExpression was used for properties that toggles the inclusion of scripts or css if a constant value is passed these inclusion were not added . By adding some additional code to setValueExpression these forces adding the required libraries, even if the final value may be empty or null, which isn't known during set.

Fixes TheCoder4eu#1098
Fixes TheCoder4eu#1052

### CODE REVIEW

**Comment by mtvweb** [comment]
Also added new datatable cdn. Fixing the strange filter mentioned in #1093

Fixes #1100

**Comment by stjheitc** [comment]
Fixes also TheCoder4eu/BootsFaces-OSP#1104

**Comment by mtvweb** [comment]
I don‘t think that it will Fix it. as an additional Note. The problem occurs only, if you use only Dynamic Values, i.E. a Page without Layout and a Single commandbutton with an awesome Icon set by el

**Comment by mtvweb** [comment]
Still not working without this pull request. If a page contains only dynamic assignments to awesome icons. It will be not included, because only a static assignment is altering the inclusion of the fontawesome includes.

**Comment by stephanrauh** [comment]
@mtvweb I tried to merge your PR yesterday. However, I'd like to exclude all the JavaScript and CSS files. I don't think they're related to any bug you've fixed. Plus, I've updated to Bootstrap 3.4.1, which probably explains the changes. I'm afraid I'm not a git pro (no pun intended!). Please apologize the inconvenience.

Is it possible to cherry-pick the Java files? Alternatively, can you update the JS and CSS files so I don't see them in the PR?

BTW, is it true you're updating the PR for three or four years now? Keep up the good work - und just ignore my embarrassed face. :)

Best regards,
Stephan

**Comment by mtvweb** [comment]
Just created a new PR, Limited to the relevant files only. So we can remove this PR, without merging it.

**Comment by stephanrauh** [comment]
I'm closing this PR in favor of #1134.

**Pull request closed without merging**
