### PR TITLE
Ajax Fixes

### PR DESCRIPTION
**Pull request by mtvweb**
Fixes ajax calls i.E. <b:dataTable var="obj" onselect="ajax:bean.select(obj)">....</b:dataTable>
or <b:dateTimePicker ondtchange="ajax:.....">. Which wrap the components in a surrounding container.

### CODE REVIEW

**Comment by stephanrauh** [comment]
Looks good. Thank you very much!

**Comment by stephanrauh** [comment]
May I mention you in the "kudos" section of the BootsFaces 1.1.0 announcement post?

**Comment by mtvweb** [comment]
Yes, of course

**Comment by stephanrauh** [comment]
Great! I've forgotten your real name. How shall I call you in the post?

**Comment by mtvweb** [comment]
Jens Heitmann

**Pull request merged**
