### PR TITLE
#662 BS feedback and error classes fixed

### LINKED ISSUE #621: Validation error style classes problem
Sorry to bother you guys, but I'm pretty sure there's a problem with error style classes.
Here's the HTML from your showcase of a input text with failed validation:
input_with_error
The issue is that the `has-error` class should be added to the `form-group` `div`, not to the `label` or `input` elements; source: http://getbootstrap.com/css/#forms-control-validation
Also, the `bf-error` class and its equivalents should be removed, or at least have no default css rules, because they override bs default styles.

### PR DESCRIPTION
**Pull request by sergiowww**
#621 error feedback classes over containers, not over fields and labels

### CODE REVIEW

**Comment by sergiowww** [comment]
Please, do not merge yet, I'll run some tests to check if there's no loose ends...

**Comment by sergiowww** [comment]
Now it is ok to merge...

**Comment by stephanrauh** [comment]
Look OK at first glance. Now for the hard task: documentation :).

**Comment by stephanrauh** [comment]
I've added some documentation for the dateTimePicker (see https://github.com/TheCoder4eu/BootsFacesWeb/commit/13b8dbd58097be43dc57e571eb8de444dbbaac7c).

**Comment by stephanrauh** [comment]
Woud you like to finish the documentation for the other components? It's mostly a simple copy and paste job, and I'd appreciate this a lot.

Thanks in advance
Stephan

**Comment by sergiowww** [comment]
Sure, I'll do it!

**Comment by stephanrauh** [comment]
@sergiowww May I mention your name in the "Kudos" section of the BootsFaces 1.1.0 announcement post?

**Comment by sergiowww** [comment]
@stephanrauh Yes! No problem... sorry I took so long to reply, it's been a rush lately!

**Pull request merged**
