### PR TITLE
Issue #285 - Mask bug caused by #279

### PR DESCRIPTION
**Pull request by XaeroDegreaz**
Masks the incompatibility referenced in #285. This serves as a temporary fix that addresses the current limitations of the new feature, and ensures that errors are logged, and handled gracefully to allow for default DataTable functionality.

### CODE REVIEW

**Comment by stephanrauh** [comment]
I have to apologize for being occupied with other things during the last couple of days (a nasty cough being one of the things that kept me busy). What's the current state of the art? Do you want us to merge both PR #284 and #286, or #286 only?

**Comment by XaeroDegreaz** [comment]
Actually both of these are good to go. I'm still needing to see if the underlying bug exists on my work project, but even if the bug shows up, it's handled gracefully.

It's possible a merge conflict will occur, and if so I'll keep an eye on it and resolve it ASAP.

Welcome back :)

**Comment by stephanrauh** [comment]
I've merged both pull request to the master branch. It looks OK to me, but I didn't run an exhaustive compatibility check yet. @XaeroDegreaz Would you like to have a look if I solved the merge conflict correctly?

Thanks in advance
Stephan

**Comment by XaeroDegreaz** [comment]
Naw you're still missing the last two commits from this PR.

I could have resolved the conflicts if I knew you would be merging them in :(

**Comment by stephanrauh** [comment]
Oops. I hope I'll find some time (and a clear head) to fix things on Saturday.

**Comment by TheCoder4eu** [comment]
Hi, I merged the changes fixing the conflicts as I guessed they were intended.
Regards,
Riccardo

**Comment by XaeroDegreaz** [comment]
I looked over the code and seems everything is in order :)

**Comment by TheCoder4eu** [comment]
Ok thanks! :-)

**Pull request merged**
