### PR TITLE
WIP: Issue #282 - Multi-column searching

### LINKED ISSUE #282: DataTable multi-column search
Add an option to enable multi-column searches.

This would add an `inputText` for each column with key events that would trigger the following API:

https://datatables.net/reference/api/column().search()

### PR DESCRIPTION
**Pull request by XaeroDegreaz**
fix #282

### CODE REVIEW

**Comment by stephanrauh** [comment]
You called this PR "WIP". Do you want me to merge it, anyways?

**Comment by XaeroDegreaz** [comment]
Nope. I just opened it up to make it easier to see the diff here. I'd like to check a couple things then I'll let ya know.

Besides, I have to reverse merge master into this branch to clear conflicts.

**Comment by stephanrauh** [comment]
Ok, and thanks for your great work!

A co-worker of mine keeps recommending this table: http://bootstrap-table.wenzhixin.net.cn/

What do you think of it?

Regards,
Stephan

**Comment by XaeroDegreaz** [comment]
> Ok, and thanks for your great work!

No, thank YOU guys for your hard work; this enhanced DataTable has made me look like a pro at work.

> A co-worker of mine keeps recommending this table: http://bootstrap-table.wenzhixin.net.cn/

> What do you think of it?

I guess it just depends on how much you really want to offer lol. The implementation you mentioned does have some added toolbars and stuff which I think are pretty cool.

However, I really do love the abundant API documentation on the site of the current implementation.

Both are really good. How badly do you want to rewrite? Hehe :D

**Comment by XaeroDegreaz** [comment]
I updated the taglib stuff by hand. I'm not entirely sure how it effects anything to be honest :)

**Comment by stephanrauh** [comment]
The taglib is important to users of Netbeans and (I think) IntelliJ Idea. Netbeans marks attributes that don't appear in the taglib as erroneous. Other IDE, such as Eclipse, are more tolerant. In Eclipse, the taglib is mostly important for the autocomplete list. And for the help texts.

JSF itself doesn't care much about the taglib. With one notable exception: it reads the taglib to determine the type of the attribute. Sometimes Integers behave differently from Strings (e.g. when evaluating EL expressions). More important, the attributes `action` and `actionListener` have special types, which behaves very differently than Strings.

**Pull request merged**
