### PR TITLE
Increase performance of b:tree control 

### PR DESCRIPTION
**Pull request by PokimonZerg**
* Disable node serialization. At now, we don't send serialized node data to the client. Because it decrease performance and have no sense. Previos realization do nothing with this data.
* We send nodeInternalId back from client. So, we can find actual node by this id.
* Pass [] empty array in case there b:tree has no value. (More natural then throwing an exception). We rely to the component realization of empty tree.

(We have faced with preformance issue then we have > 1000 nodes in this tree. So many data sends to client)

### CODE REVIEW

**Comment by stephanrauh** [comment]
I've stumbled over the same issue an hour ago. Problem is, AJAX breaks without node serialization. Please double-check if AJAX still works with your PR.

**Comment by stephanrauh** [comment]
Did you remove these lines deliberately, or is it just because you've forked before I added them?

```java 
		Node value = tree.getValue();
		if (null == value) {
			throw new FacesException("Please set the value attribute of b:tree. ClientId of the tree without value: " + clientId);
		}
```

**Comment by PokimonZerg** [comment]
AJAX still works. Tested on our corporate portal page.

Yes, I have removed this exception directly. Replaced with empty JSON array [].

**Comment by stephanrauh** [comment]
Thanks for contributing this PR!

You're lucky: we've just decided to delay the next version of BootsFaces to Monday or to next weekend. So we can merge your last-minute pull request without risk.

**Comment by stephanrauh** [comment]
@PokimonZerg May I mention your name in the "Kudos" section of the BootsFaces 1.1.0 release post?

**Pull request merged**
