### PR TITLE
#144 #288

### PR DESCRIPTION
**Pull request by lyahim**
For #288 cannot solve to usage the of converter, just add support to java8 features

### CODE REVIEW

**Comment by lyahim** [comment]
Are you support java 8?

**Comment by stephanrauh** [comment]
We support Java 6, Java 7 and everything above. Supporting features specific to Java 8 is difficult. It typically requires us to use the reflection API.

**Comment by lyahim** [comment]
Hello Stephan,

Are you see this request? What do you suggest which branch can I send the requests?

Mihaly

**Comment by stephanrauh** [comment]
Well, well, well... yes, I do see this request, and looking at the history of the request, I can see that my attempt to merge the PR to the master added a lot of confusion... Let me have a thorough look at it on Saturday. By the look of it, it'll take some time and patience to get everything straight again.

**Comment by TheCoder4eu** [comment]
Hi, IMHO the best option we have now is close this Pull request without merging, verify that master and BootsFaces-0.9.0 are ok, then do a new Pull request with the needed changes.

If the changes fix something on both master and BootsFaces-0.9.0 the PR shoud target the master and then  we'll update BootsFaces-0.9.0 accordingly.
Regards,
Riccardo

**Comment by lyahim** [comment]
Hello,
Ok, I will make a new request into master.

Best Regards,
Mihaly

**Pull request closed without merging**
