### PR TITLE
Add support for expand / collapse events in tree

### LINKED ISSUE #705: There is no support for expand / collapse events in tree control
Can't handle these events.

### PR DESCRIPTION
**Pull request by PokimonZerg**
Add special Event type and change Listener interface

Fix #705

### CODE REVIEW

**Comment by stephanrauh** [comment]
@PokimonZerg That was quick! Is this already the complete PR? In the past, I've frequently merged PRs to early, so please don't mind me asking.

Could you provide some documentation for the new feature? Preferably by sending us a pull request to the BootsFacesWeb project (which is the showcase and documentation page).

**Comment by PokimonZerg** [comment]
@stephanrauh Yes, it is the complete solution. 

Ok, I will create another PR for the showcase.

**Comment by stephanrauh** [comment]
Awesome. Thanks!

Best regards,
Stephan

**Comment by PokimonZerg** [comment]
There is a PR with showcase project changes
https://github.com/TheCoder4eu/BootsFacesWeb/pull/34

**Pull request merged**
