### PR TITLE
New formGroup component

### PR DESCRIPTION
**Pull request by ggam**
As promised, here is the formGroup component. I extended it from Row as they are basically the same thing. 

I've also updated the InputText renderer to comply with it. This is just a prototype so you @TheCoder4eu @stephanrauh can tell me if I'm going in the right direction.

I have a limited connection now and I can't download XText so I copied the jsfdsl from the row component for now.

Could you please give me any advise? If this is ok, I'll change the rest of the input renderers, although that probably should be added before the div switch we talked about in #682.

### CODE REVIEW

**Comment by stephanrauh** [comment]
At first glance, the changes look good. I'd just propose a change to the BootsFaces.jsfdsl file. Since the class is derived from `Row`, every attribute should be declared `inherited`. Otherwise, the attributes are generated although they are already in the parent class. Unfortunately, the "+" parameters can't be inherited yet - maybe I should update the Xtext generator again to support that use case.

```
widget formGroup
       implemented_by net.bootsfaces.component.formGroup.FormGroup
       has_children
       has_tooltip
 {
    dir                 inherited                                          "Direction indication for text that does not inherit directionality. Legal values: ltr (Default. Left-to-right text direction), rtl (Right-to-left text direction) and auto (let the browser figure out the direction of your alphabet, based on the page content)."
    id                  inherited                                          "Unique identifier of the component in a namingContainer."
    rendered            Boolean inherited                                  "Boolean value to specify the rendering of the component, when set to false the component will not be rendered."
    style               inherited                                          "Inline style of the input element."
    style-class         inherited                                          "Style class of this element."
    +tooltip
	+contentDisabled
}```

**Comment by stephanrauh** [comment]
The generated `FormGroup` class looks a bit different. Please add a few lines to the constructor:

```java
	public FormGroup() {
		Tooltip.addResourceFiles();
		AddResourcesListener.addThemedCSSResource("core.css");
		AddResourcesListener.addThemedCSSResource("bsf.css");
		setRendererType(DEFAULT_RENDERER);
	}
```

**Comment by stephanrauh** [comment]
You'll also need the taglib (bootsfaces-b.taglib.xml). The generator adds these lines:
```xml
	
	<!-- *********** b:formGroup ************************* -->
	<tag>
		<tag-name>formGroup</tag-name>
		<component>
			<component-type>net.bootsfaces.component.formGroup.FormGroup</component-type>
		</component>
		<attribute>
		  <description><![CDATA[Enables or disables every child element of this container. By default, child elements are enabled.]]></description>
		  <name>content-disabled</name>
		  <required>false</required>
		  <type>java.lang.Boolean</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Enables or disables every child element of this container. By default, child elements are enabled.]]></description>
		  <name>contentDisabled</name>
		  <required>false</required>
		  <type>java.lang.Boolean</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Direction indication for text that does not inherit directionality. Legal values: ltr (Default. Left-to-right text direction), rtl (Right-to-left text direction) and auto (let the browser figure out the direction of your alphabet, based on the page content).]]></description>
		  <name>dir</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Unique identifier of the component in a namingContainer.]]></description>
		  <name>id</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Boolean value to specify the rendering of the component, when set to false the component will not be rendered.]]></description>
		  <name>rendered</name>
		  <required>false</required>
		  <type>java.lang.Boolean</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Inline style of the input element.]]></description>
		  <name>style</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Style class of this element.]]></description>
		  <name>style-class</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Style class of this element.]]></description>
		  <name>styleClass</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The text of the tooltip.]]></description>
		  <name>tooltip</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Where is the tooltip div generated? That's primarily a technical value that can be used to fix rendering errors in special cases. Also see data-container in the documentation of Bootstrap. The default value is body.]]></description>
		  <name>tooltip-container</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Where is the tooltip div generated? That's primarily a technical value that can be used to fix rendering errors in special cases. Also see data-container in the documentation of Bootstrap. The default value is body.]]></description>
		  <name>tooltipContainer</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is shown and hidden with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltip-delay</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is shown and hidden with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltipDelay</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is hidden with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltip-delay-hide</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is hidden with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltipDelayHide</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is shown with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltip-delay-show</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[The tooltip is shown with a delay. This value is the delay in milliseconds. Defaults to 0 (no delay).]]></description>
		  <name>tooltipDelayShow</name>
		  <required>false</required>
		  <type>java.lang.Integer</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Where is the tooltip to be displayed? Possible values: "top", "bottom", "right", "left", "auto", "auto top", "auto bottom", "auto right" and "auto left". Default to "bottom".]]></description>
		  <name>tooltip-position</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
		<attribute>
		  <description><![CDATA[Where is the tooltip to be displayed? Possible values: "top", "bottom", "right", "left", "auto", "auto top", "auto bottom", "auto right" and "auto left". Default to "bottom".]]></description>
		  <name>tooltipPosition</name>
		  <required>false</required>
		  <type>java.lang.String</type>
		</attribute>
	</tag>
```

**Comment by stephanrauh** [comment]
One last thought: does it make sense to add support for nested input field? For example, input fields that are put into a `<h:panelGroup>` (aka `<div>`) for some reason?

And do we need to implement extra support for non-horizontal forms?

**Comment by stephanrauh** [comment]
This PR is also related to #614 and #493.

**Comment by ggam** [comment]
Thanks for the review! I had the taglib changed locally but forgot to commit it.

I've added the lines to the constructor, although I don't think it's necessary as it will anyway call the parent constructor that already does it.

As for you latest questions:
*  Support for `h:panelGrid`: how would you handle that? setting an attribute on the panelGrid to instruct inner inputs not to generate use the `form-group` class? Instead of checking if the parent component is a FormGroup, we could define a `DONT_GENERATE_FORM_GROUP_ON_INNER_INPUTS` attribute, and check for its presence on the parent component when rendering inputs. That would be provide more flexibility than the current solution. For now, Only FormGroup would have it defined, but I guess we could set it on children `panelGrids` from within the `FormGroupRenderer#encodeChildren`. Anyway, I don't think this is **necessary** at this moment. But if the attribute approach is feasible, we could make use of it in a basic fashion for now and expand it on a future release.
* Support for non horizontal forms: what changes should we need for that? For now, I think just documenting that this component only has sense for horizontal components, and logging a warning when using it on a non-horizontal one would suffice. What are you referring exactly?

**Comment by stephanrauh** [comment]
@ggam I've pushed a couple of bugfixes. I don't expect merge conflicts, but you might want to merge with the last version.

I've also found a bug. The HTML code generated by `<b:selectBooleanCheckbox>` doesn't cope with AJAX. Probably the clientID is rendered in a nested element. It needs to be with the outermost HTML element of the component. You can see the error at http://www3.bootsfaces.net/Showcase/forms/converters.jsf. Just click on "VAT" to see the bug in action.

It's exactly the source code you're already working on, so I don't want to fix it now.

> Support for h:panelGrid: how would you handle that?

Let's simply more the if statement checking for the parent form-group to a new method of the `CoreRenderer`. This way, we can decided how (or if) to implement that feature later.

> Support for non horizontal forms

Throwing a `FacesException` sounds good to me.

**Comment by ggam** [comment]
Adding to CoreRenderer a method that only affects inputs seems dirty to me. What do you think about creating a new InputRenderer that extends from CoreRenderer and adding the method there?

**Comment by ggam** [comment]
It's done now for InputText. Now I have to make it for all the other inputs and test it.

From your list on #682:

b:inputText
b:inputText with appending / prepending facet
b:colorPicker
b:colorPicker with appending / prepending facet
b:selectOneMenu
b:selectOneMenu with appending / prepending facet
b:selectMultiMenu
b:selectMultiMenu with appending / prepending facet
b:datepicker
b:datepicker with appending / prepending facet
b:dateTimePicker
b:dateTimePicker with appending / prepending facet

Also, textarea and I think some more are missing. By the time I do that, could you please review my direction? Thanks!

**Comment by stephanrauh** [comment]
I fine with creating an `InputRenderer` class. I just suggest to call it `CoreInputRenderer` to make its role more obvious and to distinguish it from the `InputRenderer` of PrimeFaces.

**Comment by stephanrauh** [comment]
> although I don't think it's necessary as it will anyway call the parent constructor that already does it.

Only if you call it :). The original implementation didn't include the `super()` call.

**Comment by stephanrauh** [comment]
I think the second ` beginDisabledFieldset(formGroup, rw);` should be an `endDisabledFieldset()`.

**Comment by stephanrauh** [comment]
I'm not sure Javadoc copes with your HTML formatting. In any case, it shows two error messages:
```
DateTimePickerRenderer.java:88: error: @param name not found
	 * @param format
	          ^
InputTextRenderer.java:61: error: @param name not found
     * @param The real attribute name of the request parameter. By default, BootsFaces guesses the attribute name
```
Maybe you can have a look at the second error because it's a class you're already working on. I'd like not to have too many merge conflicts :).

**Comment by stephanrauh** [comment]
I've modified the DateTimePicker, the ColorPicker and the Sliders slightly. Probably still no merge conflict, but pulling the current master might be a good idea.

**Comment by ggam** [comment]
I've changed the class to CoreInputRenderer. You are right about the beginDisabledFieldSet. I copied it from RowRenderer. I've fixed it for both and I pulled from master. No conflicts for now!

HTML in JavaDoc is ugly to read in code, but outputs formatted text. I can remove it if you prefer..

About the constructor, as you now, Java will always call the default parent constructor if no other is specified ;)

I'm now going to work on updating the rest of the component. Hopefully I'll be able to do it today.

**Comment by ggam** [comment]
I think I have it!

I've tested a basic version of the following components:

b:inputText
b:colorPicker
b:selectOneMenu
b:selectMultiMenu
b:datepicker
b:dateTimePicker
b:inputTextArea
b:selectOneCheckbox

At the same time, two bugs where fixed:
- ColorPicker was not rendering the label by default
- DatePicker didn't declared the label attribute. I think the getAttribute method is no present in any on the interfaces implemented by inputs. This should be checked and defined.

Could you please review this and merge if everything is ok?

**Comment by ggam** [comment]
Btw, this issue is tagged as "bug", but is really an enhancement and nothing was broken

**Comment by stephanrauh** [comment]
That was quick. Thank you very much for the good work!

**Comment by stephanrauh** [comment]
What about #614 and #493? Are they solved now, too?

**Comment by stephanrauh** [comment]
> I think the getAttribute method is no present in any on the interfaces implemented by inputs

It's a core method, probably defined in `UIComponent`. But it's old coding style, and we want to get rid of it because we've learned that calling `getAttributes()` is a simple approach, but it doesn't always work. In particular, it often fails with EL expressions. Funny thing is that it doesn't always fail.

**Pull request merged**
