### PR TITLE
add update tag to selectOneMenu

### PR DESCRIPTION
**Pull request by lyahim**

### CODE REVIEW

**Comment by stephanrauh** [comment]
So that's why I didn't find the issue I was looking for... it wasn't an issue, it was a pull request!

Sorry, Mihaly, I didn't want to dismiss your work, it was just bad luck... I appreciate your help nonetheless!

**Comment by AlexanderBl4h** [comment]
Glad you found it. I cant wait for the new version! (as always!)

**Comment by lyahim** [comment]
No problem Stephan :)
I didn't find all missing attributes.

**Comment by asterd** [comment]
Sorry Stephan, i've try to use your plugin on eclipse mars on a mac osx but it doesn't work.. Or i don't know how it works.. But eclipse does not load it..  Can you provide some hint about it please?

**Comment by stephanrauh** [comment]
I'm using it on a MacBook, too, so it's not a OS X issue. I just noticed that the files in the plugins folder are outdated - but they should work nonetheless. They just don't generate the most current version of the files. I'll upload the current version ASAP.

The idea is simple: just drop the two files of the plugins folder to the plugins folder of Eclipse. In my case, that's:
image
After restarting Eclipse, you should be able to open the file /BootsFacesMaven/xtext/BootsFaces.jsfdsl of your BootsFaces project in my editor. In other words, it should look like so:
image

**Comment by stephanrauh** [comment]
I've just updated the plugins folder of my repository. Hope it works now. BTW, I've been planning to write a blog post about my plugin for a long time. You've convinced me to put this into action :).

**Comment by asterd** [comment]
Thanks a lotm!i'll try asap! Thank you so much for your work! :)

**Comment by asterd** [comment]
Hi! finally i've used your plugin but in the old version. I cannot compile the new one because it said to me that src-gen inside de.beyondjava.xtext.jsf is missing.. can you upload also the compiled jar or tell me some hint to compile in my environment? thank you very much!

**Comment by stephanrauh** [comment]
Oh - you're right, I deleted the plugins folder instead of updating it :). Now it's there again, with the files of mid January.

**Comment by stephanrauh** [comment]
As for the compilation: You have to install XText first (from the Eclipse Marketplace).
After that you have to run the MWE2 file like shown in the screenshot:

Step 1:
step1

Step 2:
step2 - debugging


Step 3:
step3

Step 4:
step4

**Comment by asterd** [comment]
Hi! thank you very much for your hints! now it works without any problem and i can also compile! just one thing: in the de.beyondjava.xtext.jsf project, if you don't create manually an empty src-gen folder, the workflow throws an error like 'classpath resolution failed'. Creating that folder all works ok.. just to remember in the future!! :)

**Pull request closed without merging**
