### PR TITLE
Add new component ScrollUp and manage non-sticky navbar on footer

### PR DESCRIPTION
**Pull request by asterd**
This request contains code to provide a configurable scrollUp component and a simple modification to add "non-sticky" attribute to fixed property of navBar to provide bottom navbar that scroll with page but is always fixed on the bottom if the content is shorter than the window size.

### CODE REVIEW

**Comment by stephanrauh** [comment]
I believe both changes are OK. Thanks!

**Comment by asterd** [comment]
Thank you Stephan! Just for navbar-nonsticky css i hope i have put it in the right file.. Eventually can you explain in more details how to customize the project for multi theme support? The guide inside the project (cheat.sheet) seems to be incomplete and outdated.. Sorry for these requests but i believe that this project is fantastic and i hope to do somenthing for it in the best way..

**Comment by stephanrauh** [comment]
I suppose that's more than one request:
* as for the cheat.sheet: I'll have a look at it. You're right, chances are it's outdated.
* multi-theme support: doesn't http://www.bootsfaces.net/layout/themes.jsf help you? If not, what is missing?
* non-sticky css: I'll have a more thorough look at it tomorrow. My first impression was that it's good enough to be merged, but I have to admit I didn't test it. I hardly ever do such a thing - take it as a compliment :).
* Scroll-Up: we'll have to write some documentation. Can you give me some hints?

**Comment by asterd** [comment]
Ok,i got it.thank you so much!  For multi-theme support i mean in build phase of the project.. My pr works good in my tests but i don't know (or i don't understand) how to set up this custom part of css also for the "other" theme, so i can use this fuctionality even if i want to use a custom bootstrap theme. Apart that, the style work as expected. Probably i have not understood well this part of build script or i miss something else.  For scrollup i'll send you some documentation asap!

**Comment by stephanrauh** [comment]
Well... Luckily it's only 17 themes. We edit the build properties file and run the gradle script. 17 times. We want to automate this process, but we didn't manage to do it yet. Any help is appreciated!

**Pull request merged**
