### PR TITLE
Refactor AddResourcesListener and Tooltips

### PR DESCRIPTION
**Pull request by zhedar**
The AddResourcesListener currently is a bit long and contains a lot of boilerplate code, therefore I made some refactorings. ~~However, **this is still WIP, so probably shouldn't be merged yet**. For example `addJavascript` is still too long (220 lines for a single method) and the `Comparator` could be moved into an own class.~~

~~I just hoped to get some feedback (since it's getting late), e.g. on the difference between `addResourceToHeadButAfterJQuery` and `addBasicJSResource`. I couldn't spot any other than the different resource keys, but somehow I couldn't just get it to run with my extracted `addResource` method. The first seems to fail whereby the latter doesn't, so I just kept `addResourceToHeadButAfterJQuery` in place until I found the difference.~~

Changes:
* made yes / no checks more readable and fixed case errors
* extracted methods to reduce boilerplate code
* reduced nesting levels
* fixed typos

### CODE REVIEW

**Comment by zhedar** [comment]
I just added another refactoring to this PR.
This one changes the way, how Tooltip resources are added (always add tooltip.css and tooltip.js in one method call).

However, in retrospect I saw that in some cases `Tooltip.addResourceFile()` wasn't called, although the `tooltip.css` file was added. Examples for this are `Message`, `Badge` or `Messages`. In other cases, only the js file was added, e.g. in `CarouselControl` or `CarouselItem`.
Is there a specific cause why these components just need one of the files or was it just forgotten to add the other one?

**Comment by zhedar** [comment]
I just observed, that `selectOneMenu`'s tooltip isn't shown, maybe the data attributes are not set properly. This problem is already present in the [current snapshot showcase](http://www3.bootsfaces.net/Showcase/bootstrap/tooltips.jsf), so not a breaking change from my most recent changes. However, it isn't present in the [0.8.1 Showcase](http://showcase.bootsfaces.net/bootstrap/tooltips.jsf), so probably a bug we introduced in the Snapshot itself.

**Comment by zhedar** [comment]
I just tried to add an ajax listener to remove the tooltips to fix #220 and #323, but somehow this got snowballed with every ajax request, if it was added in `Tooltip.activeTooltips`.
It seems like `Tooltip.activeTooltips` is called on any ajax request as well, so I just added a quick `$('.tooltip').tooltip('destroy');` to its script.

While fixing this I discovered strange behaviour of `b:poll`, which polled just way too fast and saw #325 a lot again, I may investigate on that later on.

**Comment by zhedar** [comment]
The last commit I added(49e4a74) fixed the #325 related bug, which happened because PrimeFaces components seem to be duplicated.
The other warnings I saw came from the fact, that I used Bootstrap from CDN accidentally. We seem to remove every bsf related resource on such an occasion, which doesn't look like correct behaviour and should be fixed in the future.

I also solved the problem from the entry post and could replace two similar addResource methods by a generic one.

There's only one TODO left, before I consider this PR complete: There's still a nested if statement I marked as TODO in 49e4a74 I'd like to combine, but I'm not sure if that is actually correct as it stands, because it looks like the second statement always yields true if the first did as well.

**Comment by zhedar** [comment]
I just cleared the last open point on my list, but I would like someone to review my latest change (e6e4e46). @stephanrauh maybe? The old statement looked kind of odd. It seems like it always evaluates to true anyways, what is this needed for? Do we even need those checks?

Otherwise I would declare this PR done... before it get's an big ugly abomination of changes I stitched together :O

**Comment by stephanrauh** [comment]
Whow! That's a huge one! I'm starting to test and merge this PR.

**Comment by zhedar** [comment]
It would look smaller, if I wouldn't have named all the little changes I did and put them into separate commits though. I've tested most of this for two weeks now, so I'm rather confident that everything is going to be ok ;) Thanks for testing!

**Pull request merged**
