### PR TITLE
Fixed DateTimePicker min/max date having no effect

### PR DESCRIPTION
**Pull request by MitchTalmadge**
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/506

I found out that if the square brackets are removed, the min/max dates work as expected. I tested this and it does have the intended effect after the removal.

### CODE REVIEW

**Comment by MitchTalmadge** [comment]
I added more commits to fix the problem that the fields were not properly being disabled due to an incorrect javascript function.

Before:


After:
image

**Comment by asterd** [comment]
Thank you very much @MitchTalmadge, I've merged your PR and as soon as I'll find some free time, I'll going to review this component to improve it or fix some other little bugs.

**Comment by MitchTalmadge** [comment]
@asterd Thanks! I'd like to point out something I discovered this morning. By default, the way the datetimepicker library disables inline pickers...

image

...is to simply remove it completely. I found that a better way to do it is to give the outermost div these CSS properties:
```
opacity: 0.65;
pointer-events: none;
```

Which makes it look like this: (And nothing can be clicked)

image

So what I'd do is only add the javascript-based disabling to popup and basic type DateTimePickers, and let the inline type have those css properties instead. What do you think?

**Comment by asterd** [comment]
Hi @MitchTalmadge, i like your solution! I don't know if this can have problems with ie, but if it does not, it's look like a real good solution from an ui point-of-view. So, can you please create a new PR with this trick?

**Pull request merged**
