### PR TITLE
Added support for DateTimePicker inline disabling; Fixed DateTimePicker defaultDate not working; Fixed inline DateTimePicker not setting value correctly.

### PR DESCRIPTION
**Pull request by MitchTalmadge**
The first part of the commit adds the functionality explained here: https://github.com/TheCoder4eu/BootsFaces-OSP/pull/507#issuecomment-247788085

The second part fixes the `initialDate` attribute of DateTimePicker (which equates to `defaultDate` in javascript) having no effect in the same way that `minDate` and `maxDate` did not.

### CODE REVIEW

**Comment by MitchTalmadge** [comment]
Added another commit to solve the problem as stated here: https://github.com/TheCoder4eu/BootsFaces-OSP/issues/482

**Comment by MitchTalmadge** [comment]
Added another commit because the `date` attribute of the date time picker library was only being set on inline dateTimePickers. It really should be set on all modes:

image

If this is not set, the date chosen may not match the value passed in, which is completely unexpected. Sometimes it's the minDate, sometimes something else, but it's completely unpredictable -- even when the value is not null.

**Comment by MitchTalmadge** [comment]
Actually please hold on merging this for a bit, I need to test it a bit more.

**Comment by MitchTalmadge** [comment]
Ok, all good to merge. 

The reason for the downgrade of the javascript file is because the latest version has a bug that causes the selected time to automatically revert back to whatever it was in the beginning when switching days. Not only that, but when using minDate, times would often be disabled for selection even when they were valid, which prevented the user from selecting the desired time.

**Comment by asterd** [comment]
Hi @MitchTalmadge, thank you very much for your contribution: as I've already said, there is a lot of work to do, and sadly the time is ever the same! It would be gracefully to work more time on this project but is not always possible: so, all your contributions are well accepted, and every issue open let us improve our framework! Thank you!

**Comment by MitchTalmadge** [comment]
@asterd No worries, friend! I'm here to help. The framework you guys have created has enabled me to carry out my dreams in less time than I had ever thought possible. This is the least I can do.

**Pull request merged**
