### PR TITLE
tab anchor facet

### PR DESCRIPTION
**Pull request by dabloem**
Using a tab-facet to be more flexible in tab title. e.g. Using icons, labels, text formatting, etc...

### CODE REVIEW

**Comment by stephanrauh** [comment]
:+1:

**Comment by stephanrauh** [comment]
I added some documentation of the new feature (see http://www.bootsfaces.net/BootsFacesWeb/bootstrap/tab.jsf).

**Comment by stephanrauh** [comment]
@dabloem Thank you for contributing this feature to BootsFaces!

**Comment by TheCoder4eu** [comment]
@dabloem Thank you !

**Pull request merged**
